routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('product', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    protected $fillable = ['product_name','product_description'];


}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Variants;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Yajra\DataTables\DataTables;
use Yajra\DataTables\Html\Builder;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request,Builder $builder)
    {
        
        try{
            $products_get = Product::latest();
            



            if (request()->ajax()) {
                return DataTables::of($products_get->get())
                ->addIndexColumn()
                ->editColumn('action',function(Product $product){
                    

                     return '<a class="ml-2" href='.route('product.edit',[$product->id]).'><i class="fa fa-pencil"></i></a>';            
                })
                ->rawColumns(['action'])
                ->make(true);
            }
            $html = $builder->columns([
                ['defaultContent' => '','data' => 'DT_RowIndex','name' => 'DT_RowIndex','title' => '#','render' => null,'orderable' => false,'searchable' => false,'exportable' => false,'printable' => true,'width'=>'1%'],
                ['data' => 'product_name', 'name'    => 'product_name', 'title' => 'Product Name','width'=>'15%'],
                ['data' => 'product_description', 'name'    => 'product_description', 'title' => 'Product Description','width'=>'15%'],
                                ['data' => 'action', 'name'    => 'action', 'title' => 'action','width'=>'15%'],
                
            ])               
            
            ->parameters([
                'order' => [],
                'processing'    => true,
                'paging'        => true,
                'info'          => true,
                'searchDelay'   => 350,
                //'dom'           => 'Bfrtip',
                //'bFilter'       => false,
                //'sDom'          => 'lfrtip',
                //'buttons'       => [ 'reset', 'reload'],
                //'searching'   => true,
                ]);

            return view('product.index',compact('html','page'));
        }catch(Exception $e){
            return redirect()->back()->with([
                'status'    => 'error',
                'title'     => 'Error!!',
                'message'   => $e->getMessage()
                ]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        Product::create(['product_name'=>$request->product_name,'product_description'=>$request->product_description]);

        toastr()->success('Product addded successfully');
        return redirect('product');    
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $variants = Variants::where('product_id',$id)->get();
        return view('product.edit',compact('product','id','variants'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
         Product::where('id',$id)->update(['product_name'=>$request->product_name,'product_description'=>$request->product_description]);

        
            $files = $request->file('update_image');

         if($request->hasFile('update_image')){
                foreach ($files as $key => $file) {


                    $extension = $file->getClientOriginalExtension();
                    $filename = Str::random(10).'.'.$extension;

                    if(!empty($filename))
                    {
                            Storage::disk('public')->put('/'.$filename,  File::get($file));
                            Variants::where('id',$key)->update(['variant_image'=>$filename]);
                    }else{
                        $update_old_image = $request->update_old_image;
                        Variants::where('id',$key)->update(['variant_image'=>$update_old_image[$key]]);
                    }
                    

                }
               
            }


         
        $update_size = $request->update_size;
        foreach ($update_size as $key => $value) {
            $color = $request->update_color;
            $update_price = $request->update_price;
           Variants::where('id',$key)->update(
            ['size'=>$update_size[$key],
            'color'=>$color[$key],            
            'variant_price'=>$update_price[$key]
            ]);
         }

if($request->hasFile('image')){
                $file = $request->file('image');
                $extension = $file->getClientOriginalExtension();
                $filename = Str::random(10).'.'.$extension;
                Storage::disk('public')->put('/'.$filename,  File::get($file));
            }else{
                
                    $filename = 'avatar.png';
                
            }
            if(isset($request->size) && isset($request->color) && isset($request->price))
            {
         Variants::updateOrCreate(['product_id'=>$id,'size'=>$request->size,'color'=>$request->color],['size'=>$request->size,'color'=>$request->color,'variant_image'=>$filename,'variant_price'=>$request->price]);
         }
         return redirect('product'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

resources/views/product/create.blade.php
<form action="{{ route('product.store') }}" method="POST">
	@csrf

	Product Name: <input type="text" name="product_name" /><br>
	Product Description<textarea name="product_description"></textarea><br>
	<input type="submit" name="submit" value="Save">
</form>

resources/views/product/edit.blade.php
{!! Form::model($product,['route' => ['product.update',$id],                
                            'files' => 'true'
                        ]) !!}
	@csrf
	@method('PUT')
	Product Name: <input type="text" name="product_name" value="{{ $product->product_name }}" required="" /><br>
	Product Description<textarea name="product_description" required="">{{ $product->product_description }}</textarea><br>

	@if(isset($variants))

	@foreach($variants as $key=>$value)
	<br>
	{{ $key+1 }} Size : <input type="text" name="update_size[{{$value->id}}]" value="{{ $value->size }}"  /><br>
	{{ $key+1 }} Color: <input type="text" name="update_color[{{$value->id}}]" value="{{ $value->color }}" /><br>
	{{ $key+1 }} Price: <input type="text" name="update_price[{{$value->id}}]" value="{{ $value->variant_price }}" /><br>
	{{ $key+1 }} Image: <input type="file" name="update_image[{{$value->id}}]"  /><br><br>
	<input type="hidden" name="update_old_image[{{ $value->id }}]" value="{{ $value->variant_image }}">
	<img src={{ asset("storage/".$value->variant_image) }} height=100 width=100 /><br><br>
	@endforeach
	@endif
	<br>
	<br>
	Size : <input type="text" name="size" value=""  /><br>
	Color: <input type="text" name="color" value="" /><br>
	Price: <input type="text" name="price" value="" /><br>
	Image: <input type="file" name="image"  /><br>


<input type="submit" name="submit" value="Save">

{!! Form::close() !!}

resources/views/product/index.blade.php
<head>
    <meta charset="utf-8" />
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" href="">
    <link href="{{ asset('assets/admin/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/admin/css/icons.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/admin/css/metismenu.min.css') }}" rel="stylesheet" type="text/css" />

        
    <script src="{{ asset('assets/admin/js/modernizr.min.js') }}"></script>


    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/plugins/datatables/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/plugins/datatables/responsive.bootstrap4.min.css') }}">
    
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">

                <a class="navbar-brand" href="{{ url('/') }}">
                   Ecommerce
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            

<section class="bootstrap-checkbox" id="bootstrap-checkbox">
    <div class="row">
        <div class="col-12">
            <a href="{{ route('product.create') }}" class="btn btn-primary">Add Product</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-content collapse show">
                    <div class="card-body card-dashboard">
                        {!! $html->table(['class' => 'table table-striped table-bordered'], true) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
        </main>
    </div>

     
</body>






<script src="{{ asset('assets/admin/js/jquery.min.js') }} "></script>   
<script src="{{ asset('assets/admin/js/popper.min.js') }} "></script>
<script src="{{ asset('assets/admin/js/bootstrap.min.js') }} "></script>
<script src="{{ asset('assets/admin/js/metisMenu.min.js') }} "></script>
<script src="{{ asset('assets/admin/js/waves.js') }}"></script>

<script src="{{ asset('assets/admin/js/jquery.slimscroll.js') }} "></script>
<script src="{{ asset('assets/admin/js/jquery.core.js') }} "></script>
<script src="{{ asset('assets/admin/js/jquery.app.js') }} "></script>
<script src="{{ asset('assets/admin/plugins/sweet-alert/sweetalert2.min.js') }} "></script>
<script src="{{ asset('assets/admin/pages/jquery.sweet-alert.init.js') }} "></script>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>
    <script src="{{ asset('assets/admin/plugins/datatables/jquery.dataTables.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/plugins/datatables/dataTables.bootstrap4.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/plugins/datatables/dataTables.responsive.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/plugins/datatables/responsive.bootstrap4.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/plugins/datatables/buttons.colVis.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/plugins/datatables/buttons.html5.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/admin/plugins/datatables/buttons.print.min.js') }}" type="text/javascript"></script>
{!! $html->scripts() !!}